name: flutter-build-ios
description: Setups the environment to build ios apps with flutter
branding:
  icon: box
  color: green
  
inputs:
  working-directory:
    description: The root directory of the flutter app within this repository
    default: ./
  build-cmd:
    description: The full build command, can be used to add arguments
    default: flutter build ipa --release
  flutterfire:
    description: "Whether this project uses flutterfire, this is needed because flutterfire cli adds a post build script..."
    required: false
    default: "true" # we'll setup flutter fire just in case
  apple-id:
    description: "Your Apple ID (email)"
    required: true
  apple-id-password:
    description: "The app-specific password"
    required: true


runs:
  using: "composite"
  steps:

    - name: Check flutter found
      id: check_flutter
      shell: bash
      run: |
        if flutter --version; then
            echo "installed=true" >> "$GITHUB_OUTPUT"
        else
            echo "installed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup flutter
      if: steps.check_flutter.outputs.installed == 'false'
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true

    # this is needed because flutterfire cli adds a post build script and we want to support apps with flutterfire installed
    - name: Activate flutterfire
      if: ${{ inputs.flutterfire }} == 'true'
      run: dart pub global activate flutterfire_cli 0.3.0-dev.19 --overwrite
      shell: bash

    - name: Authenticate with Apple Developer Account
      env:
        APPLE_ID: ${{ inputs.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ inputs.APPLE_ID_PASSWORD }}
      run: |
        xcrun altool --list-providers -u "$APPLE_ID" -p "$APPLE_ID_PASSWORD"
      shell: bash


    - name: Build iOS App 
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: ${{ inputs.build-cmd }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}